name: Build OTP JInterface with Multiple JDKs

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: write
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Clone OTP repository
        run: |
          git clone https://github.com/erlang/otp.git
          cd otp
          git fetch origin maint-27:maint-27 maint-26:maint-26 maint-25:maint-25

      - name: Cache OTP repository
        uses: actions/cache/save@v4
        with:
          path: |
            otp
          key: otp-repo-${{ github.run_id }}

  build-and-release:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['maint-27', 'maint-26', 'maint-25']
        java-version: ['21']
        include:
          - branch: maint-27
            branch_suffix: otp27
          - branch: maint-26
            branch_suffix: otp26
          - branch: maint-25
            branch_suffix: otp25
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Restore cached OTP repository
        uses: actions/cache/restore@v4
        with:
          path: |
            otp
          key: otp-repo-${{ github.run_id }}
          fail-on-cache-miss: true
          
      - name: Build project
        run: |
          cd otp
          git checkout ${{ matrix.branch }}
          chmod +x ./configure
          ./configure JAVA_HOME=$JAVA_HOME
          make
          sudo make install
          
      - name: Locate and copy JAR file
        id: locate_jar
        run: |
          JINTERFACE_PATH=$(erl -noshell -eval 'io:format("~s", [code:priv_dir(jinterface)])' -s init stop)
          echo "Jinterface path: $JINTERFACE_PATH"
          
          VERSION=$(echo $JINTERFACE_PATH | grep -oP 'jinterface-\K[0-9.]+')
          echo "Found version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          sudo cp "$JINTERFACE_PATH/OtpErlang.jar" "./OtpErlang-$VERSION.jar"
          sudo chown runner:runner "./OtpErlang-$VERSION.jar"
          
      - name: Create and upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "OtpErlang.jar version ${{ steps.locate_jar.outputs.version }}" > release_notes.md
          echo "Build with:" >> release_notes.md
          echo "- OTP Branch: ${{ matrix.branch }}" >> release_notes.md
          echo "- Java Version: ${{ matrix.java-version }}" >> release_notes.md
          
          gh release create \
            "v${{ steps.locate_jar.outputs.version }}-${{ matrix.branch_suffix }}-java${{ matrix.java-version }}" \
            "./OtpErlang-${{ steps.locate_jar.outputs.version }}.jar" \
            --title "OtpErlang v${{ steps.locate_jar.outputs.version }} (${{ matrix.branch }} - Java ${{ matrix.java-version }})" \
            --notes-file release_notes.md \
            --prerelease=${{ matrix.branch != 'maint-27' }}
          
      - name: Clean up artifacts
        if: always()
        run: |
          rm -f ./OtpErlang-${{ matrix.branch_suffix }}-java${{ matrix.java-version }}-${{ steps.locate_jar.outputs.version }}.jar
          rm -f release_notes.md
